### ISSUE TITLE
GxEPD2中没有对5.83寸三色屏的定义，点不亮。。。

### ISSUE THREAD

**Issue by Lasx** [IcingTomato/eInkCalendar#2]
GxEPD2中没有对5.83寸三色屏的定义，点不亮。。。

**Comment by IcingTomato** [comment]
```cpp
GxEPD2_3C < GxEPD2_583c, GxEPD2_583c::HEIGHT / 4 > display(GxEPD2_583c(/*CS=D8*/ SS, /*DC=D3*/ 0, /*RST=D4*/ 2, /*BUSY=D2*/ 4));
```

这个应该是三色5.83的定义，手头上没有测试不了

**Comment by Lasx** [comment]
哈哈，我等不及直接换了黑白屏的。目前这套东西还是存在耗电和启动失败的问题。

**Comment by Lasx** [comment]
另外 测试了一下，待办列表还是会提示内存不足，

**Comment by IcingTomato** [comment]
> 另外 测试了一下，待办列表还是会提示内存不足，

应该不是内存不足，有可能是获取某个api的时候http code不是200或者json返回一个null导致的，内存占用88.9%左右

**Comment by Lasx** [comment]
> > 另外 测试了一下，待办列表还是会提示内存不足，
> 
> 应该不是内存不足，有可能是获取某个api的时候http code不是200或者json返回一个null导致的，内存占用88.9%左右

确实是，我在终端窗口能看到获取到了数据。这个数据里面有广告，所以我说是内存不存导致的。另外还有一个问题，如果获取不到ip，或者ip不在国内，那么屏幕不更新，而且电量消耗极快。

**Comment by IcingTomato** [comment]
还有广告？这么神奇的嘛
贴出来我瞧瞧

**Comment by Lasx** [comment]
> 还有广告？这么神奇的嘛 贴出来我瞧瞧

检查了一下，是默认的项目，全部删除就好了。但是ip这个确实是个问题。

**Comment by IcingTomato** [comment]
ip我再看看
