### ISSUE TITLE
有想法增加适配三色屏吗？

### ISSUE THREAD

**Issue by blankhub** [IcingTomato/eInkCalendar#4]
之前斥巨资买了一块7.5寸黑白黄三色屏，因为觉得黄历必须是黄的😂😂😂

结果技术有限烂尾了……
![FuN888aXHl6TP7lxQg3d7f1xR2Rkv3](https://user-images.githubusercontent.com/39051715/165893248-ee2c6603-3efd-4913-8614-61a6fc713de8.jpg)

**Comment by TinyuZhao** [comment]
即友啊

**Comment by IcingTomato** [comment]
等我发工资买一个试试
