### ISSUE TITLE
使用微雪7.5寸 三色屏build出错 求大神指点

### ISSUE THREAD

**Issue by zhukham** [IcingTomato/eInkCalendar#6]
输出错误如下：

Linking .pio\build\esp32dev\firmware.elf
c:/users/david/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\firmware.elf section `.dram0.bss' will not fit in region `dram0_0_seg'
c:/users/david/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.
c:/users/david/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.
c:/users/david/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `dram0_0_seg' overflowed by 33672 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1

**Comment by IcingTomato** [comment]
overflowed by 33672 bytes
检查一下自己的开发板还有配置文件对不对

https://github.com/IcingTomato/eInkCalendar/blob/74d06cc6731eac74099bcfe7c2588a77fd4454c1/PlatformIO/platformio.ini#L29
